name: McHomes
version: 1.1
main: com.oxology.mchomes.McHomes
api-version: 1.19
author: Oxology
description: Simple homes plugin

commands:
  home:
    description: Base command for plugin
    usage: "/home <set|teleport|remove> <name>"

permissions:
  mchomes.home.set:
    description: Allows to set home
    default: true
  mchomes.home.teleport:
    description: Allows to teleport to the home
    default: true
  mchomes.home.teleport.others:
    description: Allows to teleport to the other players home
    default: op
  mchomes.home.remove:
    description: Allows to remove homes
    default: true
  mchomes.home.list:
    description: Allows to list homes
    default: true
  mchomes.home.list.others:
    description: Allows to list other players homes
    default: op
  mchomes.home.unlimited:
    description: Allows player to set unlimited amount of homes
    default: op